theme: jekyll-theme-Cayman

<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Leiqing Li - Resume</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 20px;
    }
    
    h1 {
      font-size: 24px;
    }
    
    h2 {
      font-size: 18px;
    }
    
    .section {
      margin-bottom: 20px;
    }
    
    .section h2 {
      margin-bottom: 10px;
    }
    
    .section p {
      margin: 5px 0;
    }
    
    .list-item {
      margin: 5px 0;
    }
  </style>
</head>
<body>
  <header>
    <h1>Leiqing Li</h1>
    <p>Richmond, BC, V6X4K3</p>
    <p>Email: leiqing.li@student.kpu.ca</p>
    <p>Phone: 778-879-2253</p>
    <p>LinkedIn: <a href="https://www.linkedin.com/in/leiqing-li">linkedin.com/in/leiqing-li</a></p>
  </header>
  
  <section class="section">
    <h2>Work Experiences</h2>
    <p><strong>All Canadian Network Solutions Inc. - Telus/Koodo Sales Representative, Richmond/Vancouver</strong></p>
    <p>2023-03 - Present</p>
    <ul class="list-item">
      <li>Provide in-store and telephone customers with solutions to their cell phone or internet needs or problems.</li>
    </ul>
    <p><strong>Fantuan Delivery Driver - Fantuan Delivery, Richmond</strong></p>
    <p>2021-10 - 2023-03</p>
    <ul class="list-item">
      <li>Deliver excellent service to customers during the epidemic, maintaining a 90% on-time or early delivery rate and a 95% good rating rate.</li>
      <li>Optimize delivery routes and task sequences, resulting in a 20% time and 10% fuel savings.</li>
      <li>Communicate with customers via phone and SMS to coordinate product delivery and resolve any issues.</li>
    </ul>
  </section>
  
  <section class="section">
    <h2>Education</h2>
    <p><strong>Kwantlen Polytechnic University, Surrey - Bachelor of Information Technology</strong></p>
    <p>Expected Graduation: Summer 2023</p>
  </section>
  
  <section class="section">
    <h2>Projects</h2>
    <ul class="list-item">
      <li>Designed and implemented an organizational structure for a school group project using Windows Server 2016.</li>
      <li>Developed a food donation system website for a school group project using JavaScript, CSS, and a database.</li>
      <li>Designed and implemented a simple video game for a school group project using Processing.</li>
      <li>Designed and implemented a basic Android app for a school group project using Android Studio.</li>
    </ul>
  </section>
  
  <section class="section">
    <h2>

